<a href="../projects.html">back to projects</a>

# Append v.s. Concatenate

Here we learn two basic array manipulation techniques, append() and concatenate(). Both of the methods somehow "merge" two arrays to produce a bigger array, but there are differences for difference purposes.

## Append()

`appand()` ignores the original dimensions of the two arrays and simply produces a one-dimensional array.

In [1]:
import numpy as np

x = np.array([[0, 1], [2, 3]])
np.append(x, [[[4, 5, 6]]])

array([0, 1, 2, 3, 4, 5, 6])

So, for example, if you have to preserve the original dimension, you can reshape the output.

In [2]:
import numpy as np

x = np.array([[0, 1], [2, 3]])
x = np.append(x, [4, 5])
x = x.reshape(int(x.shape[0] / 2), 2)
x

array([[0, 1],
       [2, 3],
       [4, 5]])

## Concatenate()

`concatenate()` actually does the previous manipulations at once, if the dimensions are all the same.

In [3]:
import numpy as np

x = np.array([[0, 1], [2, 3]])
x = np.concatenate((x, [[4, 5]]))
x

array([[0, 1],
       [2, 3],
       [4, 5]])

# Using a list
`list` also has `append()` which would do what `concatenate()` does to `np.array`.

In [4]:
x = [[0, 1], [2, 3]]
x.append([4, 5])
print(x)

[[0, 1], [2, 3], [4, 5]]


The source code can be found
<a href="notebook/pytorch_basics.ipynb">here</a>.

Last edited: 2020/9/22